name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi, We welcome you, lets hope this issue will be solved soon!'
        pr-message: 'Great, This is just a start, good luck with future PRs!'
